version: "3"

services:
  hbase:
    image: dajobe/hbase
    volumes:
      - hbase-volume:/data
    ports:
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "2181:2181"
      - "16010:16010"
    labels:
      com.shinko.description: "HBase Node"
volumes:
  hbase-volume: